"""Tests for the wizard state model and IO helpers."""

from __future__ import annotations

from pathlib import Path

import pytest

from sbomify_action.cli.wizard.io import (
    WIZARD_HEADER_SENTINEL,
    WorkflowOwnershipError,
    file_has_wizard_header,
    write_workflow,
)
from sbomify_action.cli.wizard.options import WizardOptions
from sbomify_action.cli.wizard.state import (
    DiscoveredLockfile,
    Plan,
    PlannedComponent,
    RepoFacts,
    WizardState,
    WorkspaceSnapshot,
)


def _facts(tmp_path: Path) -> RepoFacts:
    return RepoFacts(
        repo_root=tmp_path,
        is_git=True,
        remote_url="git@github.com:acme/widget.git",
        suggested_repo_name="widget",
        default_branch="main",
        current_branch="main",
        has_release_tags=False,
        owner_repo_slug="acme/widget",
    )


# ----------------------------------------------------------------------
# state


def test_require_api_raises_when_unset(tmp_path: Path) -> None:
    state = WizardState(facts=_facts(tmp_path))
    with pytest.raises(RuntimeError, match="before authenticate"):
        state.require_api()


def test_wizard_state_repr_summarises(tmp_path: Path) -> None:
    state = WizardState(facts=_facts(tmp_path))
    state.workspace = WorkspaceSnapshot(products=[{"id": "p1"}])
    state.selected = [
        DiscoveredLockfile(
            path=tmp_path / "uv.lock",
            rel_path=Path("uv.lock"),
            ecosystem="python",
            suggested_name="widget-py",
        )
    ]
    rep = repr(state)
    assert "selected=1 lockfiles" in rep
    assert "workspace=<set>" in rep
    assert "api=None" in rep


def test_plan_defaults_oidc_and_skip_augmentation() -> None:
    plan = Plan()
    assert plan.credential_mode == "oidc"
    assert plan.augmentation == "skip"
    assert plan.release_strategy == "trunk"
    assert plan.create_components == []


def test_planned_component_keeps_existing_id_optional(tmp_path: Path) -> None:
    lf = DiscoveredLockfile(
        path=tmp_path / "uv.lock",
        rel_path=Path("uv.lock"),
        ecosystem="python",
        suggested_name="widget-py",
    )
    component = PlannedComponent(lockfile=lf, name="widget-py")
    assert component.existing_id is None


# ----------------------------------------------------------------------
# options


def test_wizard_options_is_frozen(tmp_path: Path) -> None:
    opts = WizardOptions(
        token=None,
        api_base_url="https://api.test",
        repo_root=tmp_path,
        output_dir=tmp_path / ".github" / "workflows",
        dry_run=False,
    )
    with pytest.raises(Exception):  # FrozenInstanceError subclasses different bases by Python version.
        opts.token = "x"  # type: ignore[misc]


# ----------------------------------------------------------------------
# io


def test_file_has_wizard_header_detects_sentinel(tmp_path: Path) -> None:
    path = tmp_path / "sboms.yml"
    path.write_text(f"# Generated by sbomify-action.\n{WIZARD_HEADER_SENTINEL}\nname: sboms\n", encoding="utf-8")
    assert file_has_wizard_header(path) is True


def test_file_has_wizard_header_returns_false_for_missing(tmp_path: Path) -> None:
    assert file_has_wizard_header(tmp_path / "absent.yml") is False


def test_file_has_wizard_header_returns_false_for_no_sentinel(tmp_path: Path) -> None:
    path = tmp_path / "sboms.yml"
    path.write_text("name: hand-authored\non:\n  push:\n", encoding="utf-8")
    assert file_has_wizard_header(path) is False


def test_write_workflow_creates_new_file(tmp_path: Path) -> None:
    path = tmp_path / ".github" / "workflows" / "sboms.yml"
    write_workflow(path, f"# header\n{WIZARD_HEADER_SENTINEL}\nname: sboms\n")
    assert path.read_text(encoding="utf-8").startswith("# header\n")


def test_write_workflow_overwrites_existing_sentinel_file_without_bak(tmp_path: Path) -> None:
    """Sentinel-tagged files get overwritten in place — no .bak, git tracks the diff."""
    path = tmp_path / "sboms.yml"
    path.write_text(f"# old\n{WIZARD_HEADER_SENTINEL}\nname: old\n", encoding="utf-8")

    write_workflow(path, f"# new\n{WIZARD_HEADER_SENTINEL}\nname: new\n")

    assert path.read_text(encoding="utf-8").startswith("# new\n")
    # We do NOT create .bak files — the previous version is recoverable via git.
    assert not path.with_suffix(path.suffix + ".bak").exists()


def test_write_workflow_refuses_to_overwrite_handauthored(tmp_path: Path) -> None:
    path = tmp_path / "sboms.yml"
    path.write_text("name: hand-authored\non:\n  push:\n", encoding="utf-8")

    with pytest.raises(WorkflowOwnershipError, match="missing"):
        write_workflow(path, f"# new\n{WIZARD_HEADER_SENTINEL}\nname: new\n")

    # Original file unchanged; no .bak either way.
    assert path.read_text(encoding="utf-8").startswith("name: hand-authored")
    assert not path.with_suffix(path.suffix + ".bak").exists()
