"""Emit GitHub Actions workflow files for the wizard.

Each lockfile maps to one workflow file. Templates are simple string
literals (no PyYAML) — they are stable enough that a templating library
adds no value.
"""

from __future__ import annotations

from pathlib import Path

from sbomify_action.cli.wizard.discovery import slugify
from sbomify_action.cli.wizard.state import (
    Plan,
    ReleaseStrategy,
    WorkflowFileAction,
)

_HEADER = (
    "# Generated by `sbomify-action wizard`.\n"
    "# TODO: OIDC token wiring is pending. Once sbomify-action supports OIDC,\n"
    "#       remove the TOKEN secret and uncomment `permissions: id-token: write`.\n"
)


def workflow_filename(component_name: str, *, component_slug: str | None = None) -> str:
    slug = component_slug or slugify(component_name) or "component"
    return f"sbomify-{slug}.yml"


def _common_env_lines(*, component_id: str, lock_file_rel: str, api_base_url: str) -> str:
    return (
        f"          TOKEN: ${{{{ secrets.SBOMIFY_TOKEN }}}}\n"
        f"          COMPONENT_ID: {component_id}\n"
        f"          COMPONENT_VERSION: ${{{{ steps.ver.outputs.v }}}}\n"
        f"          LOCK_FILE: {lock_file_rel}\n"
        f"          UPLOAD: 'true'\n"
        f"          AUGMENT: 'true'\n"
        f"          ENRICH: 'true'\n"
        f"          SBOM_FORMAT: cyclonedx\n"
        f"          API_BASE_URL: {api_base_url}\n"
    )


def _trunk_template(
    *,
    component_name: str,
    component_id: str,
    lock_file_rel: str,
    api_base_url: str,
    branch: str,
    slug: str,
    extra_top_comment: str = "",
) -> str:
    return (
        f"{_HEADER}{extra_top_comment}"
        f"name: sbomify - {component_name}\n"
        f"on:\n"
        f"  push:\n"
        f"    branches: [{branch}]\n"
        f"    paths:\n"
        f"      - '{lock_file_rel}'\n"
        f"      - '.github/workflows/sbomify-{slug}.yml'\n"
        f"  workflow_dispatch:\n"
        f"jobs:\n"
        f"  sbom:\n"
        f"    runs-on: ubuntu-latest\n"
        f"    # permissions:\n"
        f"    #   id-token: write   # uncomment when OIDC support lands\n"
        f"    steps:\n"
        f"      - uses: actions/checkout@v4\n"
        f"      - id: ver\n"
        f'        run: echo "v=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"\n'
        f"      - uses: sbomify/sbomify-action@master\n"
        f"        env:\n"
        f"{_common_env_lines(component_id=component_id, lock_file_rel=lock_file_rel, api_base_url=api_base_url)}"
    )


def _tag_template(
    *,
    component_name: str,
    component_id: str,
    product_id: str,
    lock_file_rel: str,
    api_base_url: str,
    branch: str,
    slug: str,
) -> str:
    env = _common_env_lines(component_id=component_id, lock_file_rel=lock_file_rel, api_base_url=api_base_url)
    # Splice PRODUCT_RELEASE in ahead of LOCK_FILE.
    env_with_release = env.replace(
        "          LOCK_FILE:",
        "          PRODUCT_RELEASE: ${{ steps.ver.outputs.release }}\n          LOCK_FILE:",
    )
    return (
        f"{_HEADER}"
        f"name: sbomify - {component_name}\n"
        f"on:\n"
        f"  push:\n"
        f"    branches: [{branch}]\n"
        f"    paths:\n"
        f"      - '{lock_file_rel}'\n"
        f"      - '.github/workflows/sbomify-{slug}.yml'\n"
        f"    tags: ['v*']\n"
        f"  workflow_dispatch:\n"
        f"jobs:\n"
        f"  sbom:\n"
        f"    runs-on: ubuntu-latest\n"
        f"    steps:\n"
        f"      - uses: actions/checkout@v4\n"
        f"      - id: ver\n"
        f"        run: |\n"
        f'          if [[ "$GITHUB_REF_TYPE" == "tag" ]]; then\n'
        f'            echo "v=${{GITHUB_REF_NAME}}" >> "$GITHUB_OUTPUT"\n'
        f'            echo \'release=["{product_id}:\'"${{GITHUB_REF_NAME}}"\'"]\' >> "$GITHUB_OUTPUT"\n'
        f"          else\n"
        f'            echo "v=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"\n'
        f'            echo "release=" >> "$GITHUB_OUTPUT"\n'
        f"          fi\n"
        f"      - uses: sbomify/sbomify-action@master\n"
        f"        env:\n"
        f"{env_with_release}"
    )


def _manual_template(
    *,
    component_name: str,
    component_id: str,
    lock_file_rel: str,
    api_base_url: str,
) -> str:
    env = _common_env_lines(component_id=component_id, lock_file_rel=lock_file_rel, api_base_url=api_base_url)
    return (
        f"{_HEADER}"
        f"name: sbomify - {component_name}\n"
        f"on:\n"
        f"  workflow_dispatch:\n"
        f"    inputs:\n"
        f"      version:\n"
        f"        description: 'Version label for this SBOM (blank = git short SHA).'\n"
        f"        required: false\n"
        f"        default: ''\n"
        f"jobs:\n"
        f"  sbom:\n"
        f"    runs-on: ubuntu-latest\n"
        f"    steps:\n"
        f"      - uses: actions/checkout@v4\n"
        f"      - id: ver\n"
        f"        run: |\n"
        f'          if [[ -n "${{{{ inputs.version }}}}" ]]; then\n'
        f'            echo "v=${{{{ inputs.version }}}}" >> "$GITHUB_OUTPUT"\n'
        f"          else\n"
        f'            echo "v=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"\n'
        f"          fi\n"
        f"      - uses: sbomify/sbomify-action@master\n"
        f"        env:\n"
        f"{env}"
    )


def render_workflow(
    *,
    component_name: str,
    component_id: str,
    product_id: str,
    lock_file_rel: str,
    api_base_url: str,
    release_strategy: ReleaseStrategy,
    default_branch: str = "main",
    component_slug: str | None = None,
) -> str:
    slug = component_slug or slugify(component_name) or "component"

    if release_strategy == "tag":
        return _tag_template(
            component_name=component_name,
            component_id=component_id,
            product_id=product_id,
            lock_file_rel=lock_file_rel,
            api_base_url=api_base_url,
            branch=default_branch,
            slug=slug,
        )
    if release_strategy == "manual":
        return _manual_template(
            component_name=component_name,
            component_id=component_id,
            lock_file_rel=lock_file_rel,
            api_base_url=api_base_url,
        )

    # latest / none — same template; 'none' adds a top comment.
    extra_comment = ""
    if release_strategy == "none":
        extra_comment = (
            "# Note: release tracking is disabled for this component. Re-run\n"
            "#       `sbomify-action wizard` to switch to git-tag or manual.\n"
        )
    return _trunk_template(
        component_name=component_name,
        component_id=component_id,
        lock_file_rel=lock_file_rel,
        api_base_url=api_base_url,
        branch=default_branch,
        slug=slug,
        extra_top_comment=extra_comment,
    )


def plan_workflow_files(
    *,
    plan: Plan,
    output_dir: Path,
    api_base_url: str,
    default_branch: str,
    product_id: str,
    component_ids: dict[Path, str] | None = None,
) -> list[tuple[Path, str, WorkflowFileAction]]:
    """Build the (path, content, action) list for each component.

    ``component_ids`` is the mapping {lockfile_rel_path -> created component id}
    once components have been created. While planning (Phase 5), pass an
    empty mapping; the placeholder ``<component-id>`` is written and the
    real ID is substituted at apply time.
    """
    component_ids = component_ids or {}
    items: list[tuple[Path, str, WorkflowFileAction]] = []
    for planned in plan.create_components:
        slug = slugify(planned.name) or "component"
        path = output_dir / workflow_filename(planned.name, component_slug=slug)
        content = render_workflow(
            component_name=planned.name,
            component_id=component_ids.get(planned.lockfile.rel_path, "<component-id>"),
            product_id=product_id,
            lock_file_rel=str(planned.lockfile.rel_path).replace("\\", "/"),
            api_base_url=api_base_url,
            release_strategy=planned.release_strategy,
            default_branch=default_branch,
            component_slug=slug,
        )
        action: WorkflowFileAction = "write"
        if path.exists():
            action = "skip"
        items.append((path, content, action))
    return items


def write_workflow_files(
    files: list[tuple[Path, str, WorkflowFileAction]],
    *,
    dry_run: bool = False,
) -> list[Path]:
    """Apply the planned workflow files. Returns the paths actually written."""
    written: list[Path] = []
    for path, content, action in files:
        if action == "skip":
            continue
        target = path
        if action == "write_new":
            target = path.with_name(path.name + ".new")
        if dry_run:
            written.append(target)
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        with open(target, "w", encoding="utf-8") as f:
            f.write(content)
        written.append(target)
    return written
