"""Render the wizard's GitHub Actions workflow file.

The wizard owns one filename: ``.github/workflows/sboms.yml``. Every
selected lockfile becomes a matrix entry in a single job, so all
components in one repo share one release-strategy + credential-mode +
augmentation setting. That's the explicit scope simplification —
multi-strategy emission lives outside the wizard.

Templates are plain f-strings. PyYAML round-tripping silently mangles
quoting of GitHub Actions expressions (``${{ … }}``) and reorders keys,
which would force snapshot churn for cosmetic-only changes.
"""

from __future__ import annotations

from sbomify_action.cli.wizard.discovery import slugify
from sbomify_action.cli.wizard.state import (
    CredentialMode,
    Plan,
    PlannedComponent,
    ReleaseStrategy,
    RepoFacts,
)

# Bump these together when cutting a new sbomify-action release. The
# pinned SHA is the security guarantee per SECURITY.md — emitted
# workflows reference @<sha> rather than @<tag> so a tag rewrite can't
# silently swap the action's code under the user.
PINNED_ACTION_SHA = "ac8b0d423c90447f3011ef8ab5f9ff2e854c6931"
PINNED_ACTION_VERSION = "v26.2.0"

# Sentinel comment that wizard-managed files carry. Detection (in
# ``existing.py``) uses this to refuse to overwrite hand-authored
# workflows.
HEADER_SENTINEL = "# sbomify-action wizard v1"

_GENERATED_HEADER = f"# Generated by `sbomify-action wizard`. Re-run the wizard to update.\n{HEADER_SENTINEL}\n"


def _matrix_block(components: list[PlannedComponent], component_ids: dict[str, str]) -> str:
    """Render the ``matrix.include:`` rows for the planned components.

    ``component_ids`` is keyed by lockfile rel_path string so callers
    can pass either the post-apply ID map or pre-apply placeholders.
    """
    rows: list[str] = []
    for c in components:
        slug = slugify(c.name) or "component"
        rel = str(c.lockfile.rel_path)
        cid = component_ids.get(rel, c.existing_id or "REPLACE_WITH_COMPONENT_ID")
        rows.append(
            "          - name: " + slug + "\n            component_id: " + cid + "\n            lockfile: " + rel + "\n"
        )
    return "".join(rows)


def _trigger_block(strategy: ReleaseStrategy, branch: str, lockfile_paths: list[str]) -> str:
    """``on:`` block — picks push branches vs. tags vs. workflow_dispatch."""
    paths_lines = "".join(f"      - '{p}'\n" for p in lockfile_paths)
    paths_lines += "      - '.github/workflows/sboms.yml'\n"
    if strategy == "trunk":
        return f"on:\n  push:\n    branches: [{branch}]\n    paths:\n{paths_lines}  workflow_dispatch:\n"
    if strategy == "tag":
        return "on:\n  push:\n    tags: ['v*']\n  workflow_dispatch:\n"
    # manual
    return "on:\n  workflow_dispatch:\n"


def _version_step(strategy: ReleaseStrategy) -> str:
    """Compute the ``COMPONENT_VERSION`` for the matrix job's step output.

    - tag → strip ``refs/tags/`` from ``GITHUB_REF`` (clean semver).
    - trunk/manual → short SHA so each push gets a unique version
      without clashing.
    """
    if strategy == "tag":
        return '      - id: ver\n        run: echo "v=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"\n'
    return '      - id: ver\n        run: echo "v=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"\n'


def _permissions_block(mode: CredentialMode) -> str:
    """OIDC mode requires ``id-token: write`` so the runner can mint a JWT."""
    if mode == "oidc":
        return (
            "    permissions:\n      id-token: write   # required to mint the GitHub OIDC JWT\n      contents: read\n"
        )
    return ""


def _env_block(
    *,
    api_base_url: str,
    credential_mode: CredentialMode,
    augmentation: str,
    release_strategy: ReleaseStrategy,
    product_id: str | None,
) -> str:
    """The ``env:`` block under the action step.

    Token mode adds ``TOKEN: ${{ secrets.SBOMIFY_TOKEN }}``; OIDC mode
    drops it entirely (the action mints a short-lived token from the
    OIDC JWT at runtime).

    ``PRODUCT_RELEASE`` is only set for tag-strategy emissions where a
    product was selected; without it the action runs in upload-only
    mode.
    """
    lines: list[str] = []
    if credential_mode == "token":
        lines.append("          TOKEN: ${{ secrets.SBOMIFY_TOKEN }}")
    lines.extend(
        [
            "          COMPONENT_ID: ${{ matrix.component_id }}",
            "          COMPONENT_VERSION: ${{ steps.ver.outputs.v }}",
            "          LOCK_FILE: ${{ matrix.lockfile }}",
            "          UPLOAD: 'true'",
            f"          AUGMENT: '{augmentation_to_env(augmentation)}'",
            "          ENRICH: 'true'",
            "          SBOM_FORMAT: cyclonedx",
            f"          API_BASE_URL: {api_base_url}",
        ]
    )
    if release_strategy == "tag" and product_id:
        lines.append(f"          PRODUCT_RELEASE: '{product_id}:${{{{ steps.ver.outputs.v }}}}'")
    return "\n".join(lines) + "\n"


def augmentation_to_env(value: str) -> str:
    """Map the wizard's AugmentationStrategy literal to the action env flag."""
    return "true" if value == "profile" else "false"


def emit_workflow(
    plan: Plan,
    *,
    facts: RepoFacts,
    api_base_url: str,
    component_ids: dict[str, str] | None = None,
) -> str:
    """Render the wizard's ``sboms.yml`` for ``plan``.

    ``component_ids`` is a ``{rel_path_str: id}`` map populated by the
    apply phase once the matching components have been created.
    Pre-apply (review screen, dry-run, snapshot tests) it can be
    omitted; the emitter falls back to the planned component's
    ``existing_id`` or a literal ``REPLACE_WITH_COMPONENT_ID``
    placeholder.
    """
    component_ids = component_ids or {}
    lockfile_paths = [str(c.lockfile.rel_path) for c in plan.create_components]

    permissions = _permissions_block(plan.credential_mode)
    trigger = _trigger_block(plan.release_strategy, facts.default_branch, lockfile_paths)
    version_step = _version_step(plan.release_strategy)
    env = _env_block(
        api_base_url=api_base_url,
        credential_mode=plan.credential_mode,
        augmentation=plan.augmentation,
        release_strategy=plan.release_strategy,
        product_id=plan.use_product_id,
    )
    matrix = _matrix_block(plan.create_components, component_ids)

    return (
        f"{_GENERATED_HEADER}"
        "name: sboms\n"
        f"{trigger}"
        "jobs:\n"
        "  sbom:\n"
        "    name: ${{ matrix.name }}\n"
        "    runs-on: ubuntu-latest\n"
        f"{permissions}"
        "    strategy:\n"
        "      fail-fast: false\n"
        "      matrix:\n"
        "        include:\n"
        f"{matrix}"
        "    steps:\n"
        "      - uses: actions/checkout@v4\n"
        f"{version_step}"
        f"      - uses: sbomify/sbomify-action@{PINNED_ACTION_SHA}  # {PINNED_ACTION_VERSION}\n"
        "        env:\n"
        f"{env}"
    )
